"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/agent.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class AgentPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/agent"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'agents': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agents'}, {'strategy': 'text', 'value': 'Agents', 'role': 'button'}],
        'prompts': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Prompts'}, {'strategy': 'text', 'value': 'Prompts', 'role': 'button'}],
        'search_agents': [{'strategy': 'placeholder', 'value': 'Search Agents...', 'role': 'textbox'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_2_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_3_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_4_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_5_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_6_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_7_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[7]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_8_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[8]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_9_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[9]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_10_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[10]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_11_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_12_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[12]/div[1]/button[1]', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to home section"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie feature"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Open Data Catalog section"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection section"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Open Data Quality section"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines section"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Open Agent Management section"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security section"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications section"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Log out of the application"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """Close the sidebar menu"""
        self.click('close_sidebar')

    def click_agents(self) -> None:
        """Open Agents section"""
        self.click('agents')

    def click_prompts(self) -> None:
        """Open Prompts section"""
        self.click('prompts')

    def fill_search_agents(self, value: str) -> None:
        """Search for agents"""
        self.fill('search_agents', value)
