"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/catalog.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests import settings
from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class CatalogPage(BasePage):
    # Path component only — the absolute URL is built at runtime from
    # ``settings.BASE_URL`` so the same POM targets dev / staging / prod
    # without regeneration. The extraction URL captured at generation
    # time was: https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/catalog
    PATH = "/catalog"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'data_catalog_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'glossary': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Glossary'}, {'strategy': 'text', 'value': 'Glossary', 'role': 'button'}],
        'search_assets': [{'strategy': 'placeholder', 'value': 'Search Assets', 'role': 'textbox'}],
        'filter': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Filter'}, {'strategy': 'text', 'value': 'Filter', 'role': 'button'}],
        'previous': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Previous'}, {'strategy': 'text', 'value': 'Previous', 'role': 'button'}],
        '_1': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '1'}, {'strategy': 'text', 'value': '1', 'role': 'button'}],
        '_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '2'}, {'strategy': 'text', 'value': '2', 'role': 'button'}],
        '_192': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '192'}, {'strategy': 'text', 'value': '192', 'role': 'button'}],
        'next': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Next'}, {'strategy': 'text', 'value': 'Next', 'role': 'button'}],
        'open_stewie_assistant': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Open Stewie assistant'}, {'strategy': 'label', 'value': 'Open Stewie assistant', 'role': 'button', 'name': 'Open Stewie assistant'}, {'strategy': 'text', 'value': 'Open Stewie assistant', 'role': 'button'}],
        'heading_catalog': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'Catalog'}, {'strategy': 'text', 'value': 'Catalog', 'role': 'heading'}],
        'home_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'notifications_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    @property
    def URL(self) -> str:
        """Absolute URL for this page, joined against ``settings.BASE_URL``.

        Raises if ``BASE_URL`` is empty so a missing ``.env`` entry
        fails loudly instead of silently hitting ``about:blank`` or
        whatever Playwright does with a bare path.
        """
        base = (settings.BASE_URL or "").rstrip("/")
        if not base:
            raise RuntimeError(
                "BASE_URL is not set in .env — add it so tests target "
                "your environment (dev / staging / prod)."
            )
        return base + self.PATH

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """navigate to home dashboard"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """open Stewie AI assistant"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """view data catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """manage source connections"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """view data quality dashboard"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """manage agent pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """manage agents"""
        self.click('agent_management')

    def click_security(self) -> None:
        """access security settings"""
        self.click('security')

    def click_notifications(self) -> None:
        """view notifications"""
        self.click('notifications')

    def click_logout(self) -> None:
        """logout of Stewie AI"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """close sidebar navigation"""
        self.click('close_sidebar')

    def click_data_catalog_secondary(self) -> None:
        """view data catalog (secondary)"""
        self.click('data_catalog_2')

    def click_glossary(self) -> None:
        """open glossary"""
        self.click('glossary')

    def fill_search_assets(self, value: str) -> None:
        """fill search assets textbox"""
        self.fill('search_assets', value)

    def submit_search_assets(self) -> None:
        """submit asset search via Enter key"""
        self.locate('search_assets').press('Enter')

    def click_filter(self) -> None:
        """apply filter to results"""
        self.click('filter')

    def click_previous_page(self) -> None:
        """go to previous results page"""
        self.click('previous')

    def click_page_1(self) -> None:
        """go to page 1 of results"""
        self.click('_1')

    def click_page_2(self) -> None:
        """go to page 2 of results"""
        self.click('_2')

    def click_page_192(self) -> None:
        """go to page 192 of results"""
        self.click('_192')

    def click_next_page(self) -> None:
        """go to next results page"""
        self.click('next')

    def click_open_stewie_assistant(self) -> None:
        """open Stewie assistant chat"""
        self.click('open_stewie_assistant')

    def click_home_secondary(self) -> None:
        """navigate to home dashboard (secondary)"""
        self.click('home_2')

    def click_notifications_secondary(self) -> None:
        """view notifications (secondary)"""
        self.click('notifications_2')

    def click_logout_secondary(self) -> None:
        """logout of Stewie AI (secondary)"""
        self.click('logout_2')

    def expect_heading_catalog(self) -> None:
        """assert Catalog heading is visible"""
        expect(self.locate('heading_catalog')).to_be_visible()
