"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/catalog.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class CatalogPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/catalog"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'data_catalog_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'glossary': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Glossary'}, {'strategy': 'text', 'value': 'Glossary', 'role': 'button'}],
        'search_assets': [{'strategy': 'placeholder', 'value': 'Search Assets', 'role': 'textbox'}],
        'filter': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Filter'}, {'strategy': 'text', 'value': 'Filter', 'role': 'button'}],
        'previous': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Previous'}, {'strategy': 'text', 'value': 'Previous', 'role': 'button'}],
        '_1': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '1'}, {'strategy': 'text', 'value': '1', 'role': 'button'}],
        '_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '2'}, {'strategy': 'text', 'value': '2', 'role': 'button'}],
        '_4': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '4'}, {'strategy': 'text', 'value': '4', 'role': 'button'}],
        'next': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Next'}, {'strategy': 'text', 'value': 'Next', 'role': 'button'}],
        'open_stewie_assistant': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Open Stewie assistant'}, {'strategy': 'label', 'value': 'Open Stewie assistant', 'role': 'button', 'name': 'Open Stewie assistant'}, {'strategy': 'text', 'value': 'Open Stewie assistant', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to Home section"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie dialog"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Go to Data Catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Go to Data Quality section"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Go to Agent Management"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security section"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications panel"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Log out of application"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """Close the sidebar"""
        self.click('close_sidebar')

    def click_glossary(self) -> None:
        """Open Glossary section"""
        self.click('glossary')

    def fill_search_assets(self, value: str) -> None:
        """Enter search term for assets"""
        self.fill('search_assets', value)

    def click_filter(self) -> None:
        """Open filter options"""
        self.click('filter')

    def click_previous(self) -> None:
        """Go to previous page"""
        self.click('previous')

    def click_page_1(self) -> None:
        """Go to page 1"""
        self.click('_1')

    def click_page_2(self) -> None:
        """Go to page 2"""
        self.click('_2')

    def click_page_4(self) -> None:
        """Go to page 4"""
        self.click('_4')

    def click_next(self) -> None:
        """Go to next page"""
        self.click('next')

    def click_open_stewie_assistant(self) -> None:
        """Open Stewie assistant"""
        self.click('open_stewie_assistant')
