"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/dq/insights.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class DqInsightsPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/dq/insights"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'dashboards': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Dashboards'}, {'strategy': 'text', 'value': 'Dashboards', 'role': 'button'}],
        'rule_library': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Rule Library'}, {'strategy': 'text', 'value': 'Rule Library', 'role': 'button'}],
        'rule_set': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Rule Set'}, {'strategy': 'text', 'value': 'Rule Set', 'role': 'button'}],
        'rule_set_monitor': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Rule Set Monitor'}, {'strategy': 'text', 'value': 'Rule Set Monitor', 'role': 'button'}],
        'create_dashboard': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Create Dashboard'}, {'strategy': 'text', 'value': 'Create Dashboard', 'role': 'button'}],
        'search_dashboard': [{'strategy': 'placeholder', 'value': 'Search Dashboard', 'role': 'textbox'}],
        'public_dashboards_4': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Public Dashboards (4)'}, {'strategy': 'text', 'value': 'Public Dashboards (4)', 'role': 'button'}],
        'my_dashboards_0': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'My Dashboards (0)'}, {'strategy': 'text', 'value': 'My Dashboards (0)', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_1_div_1_div_1_div_1_div_2_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_2_div_1_div_1_div_1_div_2_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_3_div_1_div_1_div_1_div_2_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_2_div_1_div_4_div_1_div_1_div_1_div_2_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/button[1]', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to Home"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Open Data Catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Open Data Quality"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Open Agent Management"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Logout user"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """Close sidebar menu"""
        self.click('close_sidebar')

    def click_dashboards(self) -> None:
        """Open Dashboards"""
        self.click('dashboards')

    def click_rule_library(self) -> None:
        """Open Rule Library"""
        self.click('rule_library')

    def click_rule_set(self) -> None:
        """Open Rule Set"""
        self.click('rule_set')

    def click_rule_set_monitor(self) -> None:
        """Open Rule Set Monitor"""
        self.click('rule_set_monitor')

    def click_create_dashboard(self) -> None:
        """Create new dashboard"""
        self.click('create_dashboard')

    def fill_search_dashboard(self, value: str) -> None:
        """Search dashboards"""
        self.fill('search_dashboard', value)

    def click_public_dashboards(self) -> None:
        """Show public dashboards"""
        self.click('public_dashboards_4')

    def click_my_dashboards(self) -> None:
        """Show my dashboards"""
        self.click('my_dashboards_0')
