"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/home.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests import settings
from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class HomePage(BasePage):
    # Path component only — the absolute URL is built at runtime from
    # ``settings.BASE_URL`` so the same POM targets dev / staging / prod
    # without regeneration. The extraction URL captured at generation
    # time was: https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/home
    PATH = "/home"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'refresh': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Refresh'}, {'strategy': 'text', 'value': 'Refresh', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_1_div_2_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_1_div_2_button_3': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[3]', 'role': 'button'}],
        'search_for_assets_terms_rules': [{'strategy': 'placeholder', 'value': 'Search for Assets, Terms, Rules...', 'role': 'textbox'}],
        'find_pii_risks': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Find PII risks'}, {'strategy': 'text', 'value': 'Find PII risks', 'role': 'button'}],
        'show_failing_rule_sets': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Show failing rule sets'}, {'strategy': 'text', 'value': 'Show failing rule sets', 'role': 'button'}],
        'pending_certification': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Pending certification'}, {'strategy': 'text', 'value': 'Pending certification', 'role': 'button'}],
        'gold_riskclassification_and_retentionperiod': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'gold — RiskClassification and RetentionPeriod'}, {'strategy': 'text', 'value': 'gold — RiskClassification and RetentionPeriod', 'role': 'button'}],
        'd_calendar_riskclassification_and_retentionperiod': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'd_calendar — RiskClassification and RetentionPeriod'}, {'strategy': 'text', 'value': 'd_calendar — RiskClassification and RetentionPeriod', 'role': 'button'}],
        'view_all': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View all'}, {'strategy': 'text', 'value': 'View all', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'all': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'All'}, {'strategy': 'text', 'value': 'All', 'role': 'button'}],
        'ownership': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ownership'}, {'strategy': 'text', 'value': 'Ownership', 'role': 'button'}],
        'tags': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Tags'}, {'strategy': 'text', 'value': 'Tags', 'role': 'button'}],
        'pii': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'PII'}, {'strategy': 'text', 'value': 'PII', 'role': 'button'}],
        'rules': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Rules'}, {'strategy': 'text', 'value': 'Rules', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_2_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[2]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_3_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[3]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_4_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[4]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_5_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[5]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_6_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[6]/button[1]', 'role': 'button'}],
        'view_all_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View all'}, {'strategy': 'text', 'value': 'View all', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_3_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[3]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'ask_stewie_about_assets_rules_domains': [{'strategy': 'placeholder', 'value': 'Ask Stewie about assets, rules, domains...', 'role': 'textbox'}],
        'view_full_chat_history': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View full chat history'}, {'strategy': 'text', 'value': 'View full chat history', 'role': 'button'}],
        'ask': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask'}, {'strategy': 'text', 'value': 'Ask', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_3_div_2_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[3]/div[2]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_3_div_2_div_2_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[3]/div[2]/div[2]/div[1]/button[1]', 'role': 'button'}],
        'view_all_3': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View all'}, {'strategy': 'text', 'value': 'View all', 'role': 'button'}],
        'heading_stewie_terminal': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'Stewie Terminal'}, {'strategy': 'text', 'value': 'Stewie Terminal', 'role': 'heading'}],
        'heading_my_domain_health': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'My Domain Health'}, {'strategy': 'text', 'value': 'My Domain Health', 'role': 'heading'}],
        'heading_activity_feed': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'Activity Feed'}, {'strategy': 'text', 'value': 'Activity Feed', 'role': 'heading'}],
        'heading_ask_stewie': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'heading'}],
        'heading_admin_actions': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'Admin Actions'}, {'strategy': 'text', 'value': 'Admin Actions', 'role': 'heading'}],
        'heading_dq_failures': [{'strategy': 'role_name', 'value': 'heading', 'role': 'heading', 'name': 'DQ Failures'}, {'strategy': 'text', 'value': 'DQ Failures', 'role': 'heading'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    @property
    def URL(self) -> str:
        """Absolute URL for this page, joined against ``settings.BASE_URL``.

        Raises if ``BASE_URL`` is empty so a missing ``.env`` entry
        fails loudly instead of silently hitting ``about:blank`` or
        whatever Playwright does with a bare path.
        """
        base = (settings.BASE_URL or "").rstrip("/")
        if not base:
            raise RuntimeError(
                "BASE_URL is not set in .env — add it so tests target "
                "your environment (dev / staging / prod)."
            )
        return base + self.PATH

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """navigate to home dashboard"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """open Ask Stewie dialog"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """open Data Catalog section"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """open Source Connection section"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """open Data Quality section"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """open Agent Pipelines section"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """open Agent Management section"""
        self.click('agent_management')

    def click_security(self) -> None:
        """open Security section"""
        self.click('security')

    def click_notifications(self) -> None:
        """open Notifications panel"""
        self.click('notifications')

    def click_logout(self) -> None:
        """log out of Stewie AI"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """close sidebar navigation"""
        self.click('close_sidebar')

    def click_refresh(self) -> None:
        """refresh dashboard data"""
        self.click('refresh')

    def fill_search_for_assets_terms_rules(self, value: str) -> None:
        """fill search textbox for assets, terms, rules"""
        self.fill('search_for_assets_terms_rules', value)

    def submit_search_for_assets_terms_rules(self) -> None:
        """submit search via Enter key"""
        self.locate('search_for_assets_terms_rules').press('Enter')

    def fill_ask_stewie_about_assets_rules_domains(self, value: str) -> None:
        """fill Ask Stewie chat textbox"""
        self.fill('ask_stewie_about_assets_rules_domains', value)

    def submit_ask_stewie_about_assets_rules_domains(self) -> None:
        """submit Ask Stewie chat via Enter key"""
        self.locate('ask_stewie_about_assets_rules_domains').press('Enter')

    def click_find_pii_risks(self) -> None:
        """find PII risks"""
        self.click('find_pii_risks')

    def click_show_failing_rule_sets(self) -> None:
        """show failing rule sets"""
        self.click('show_failing_rule_sets')

    def click_pending_certification(self) -> None:
        """view pending certification"""
        self.click('pending_certification')

    def click_gold_riskclassification_and_retentionperiod(self) -> None:
        """view gold RiskClassification and RetentionPeriod"""
        self.click('gold_riskclassification_and_retentionperiod')

    def click_d_calendar_riskclassification_and_retentionperiod(self) -> None:
        """view d_calendar RiskClassification and RetentionPeriod"""
        self.click('d_calendar_riskclassification_and_retentionperiod')

    def click_view_all(self) -> None:
        """view all items"""
        self.click('view_all')

    def click_all(self) -> None:
        """filter by All"""
        self.click('all')

    def click_ownership(self) -> None:
        """filter by Ownership"""
        self.click('ownership')

    def click_tags(self) -> None:
        """filter by Tags"""
        self.click('tags')

    def click_pii(self) -> None:
        """filter by PII"""
        self.click('pii')

    def click_rules(self) -> None:
        """filter by Rules"""
        self.click('rules')

    def click_view_all_2(self) -> None:
        """view all items (second instance)"""
        self.click('view_all_2')

    def click_view_full_chat_history(self) -> None:
        """view full chat history"""
        self.click('view_full_chat_history')

    def click_ask(self) -> None:
        """submit Ask Stewie chat"""
        self.click('ask')

    def click_view_all_3(self) -> None:
        """view all items (third instance)"""
        self.click('view_all_3')

    def expect_heading_stewie_terminal(self) -> None:
        """assert Stewie Terminal heading is visible"""
        expect(self.locate('heading_stewie_terminal')).to_be_visible()

    def expect_heading_my_domain_health(self) -> None:
        """assert My Domain Health heading is visible"""
        expect(self.locate('heading_my_domain_health')).to_be_visible()

    def expect_heading_activity_feed(self) -> None:
        """assert Activity Feed heading is visible"""
        expect(self.locate('heading_activity_feed')).to_be_visible()

    def expect_heading_ask_stewie(self) -> None:
        """assert Ask Stewie heading is visible"""
        expect(self.locate('heading_ask_stewie')).to_be_visible()

    def expect_heading_admin_actions(self) -> None:
        """assert Admin Actions heading is visible"""
        expect(self.locate('heading_admin_actions')).to_be_visible()

    def expect_heading_dq_failures(self) -> None:
        """assert DQ Failures heading is visible"""
        expect(self.locate('heading_dq_failures')).to_be_visible()
