"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/home.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class HomePage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/home"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'refresh': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Refresh'}, {'strategy': 'text', 'value': 'Refresh', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_1_div_2_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_1_div_2_button_3': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[3]', 'role': 'button'}],
        'search_assets_terms_rules_type_for_suggestions': [{'strategy': 'placeholder', 'value': 'Search Assets, Terms, Rules... (Type @ for suggestions)', 'role': 'textbox'}],
        'find_pii_risks': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Find PII risks'}, {'strategy': 'text', 'value': 'Find PII risks', 'role': 'button'}],
        'show_failing_rule_sets': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Show failing rule sets'}, {'strategy': 'text', 'value': 'Show failing rule sets', 'role': 'button'}],
        'pending_certification': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Pending certification'}, {'strategy': 'text', 'value': 'Pending certification', 'role': 'button'}],
        'account_riskclassification_and_retentionperiod': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'ACCOUNT — RiskClassification and RetentionPeriod'}, {'strategy': 'text', 'value': 'ACCOUNT — RiskClassification and RetentionPeriod', 'role': 'button'}],
        'account_account_relation_riskclassification_and_retentionperiod': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'ACCOUNT_ACCOUNT_RELATION — RiskClassification and RetentionPeriod'}, {'strategy': 'text', 'value': 'ACCOUNT_ACCOUNT_RELATION — RiskClassification and RetentionPeriod', 'role': 'button'}],
        'view_all': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View all'}, {'strategy': 'text', 'value': 'View all', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'all': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'All'}, {'strategy': 'text', 'value': 'All', 'role': 'button'}],
        'ownership': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ownership'}, {'strategy': 'text', 'value': 'Ownership', 'role': 'button'}],
        'tags': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Tags'}, {'strategy': 'text', 'value': 'Tags', 'role': 'button'}],
        'pii': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'PII'}, {'strategy': 'text', 'value': 'PII', 'role': 'button'}],
        'rules': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Rules'}, {'strategy': 'text', 'value': 'Rules', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_2_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[2]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_3_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[3]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_4_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[4]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_5_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[5]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_2_div_1_div_3_div_6_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[2]/div[1]/div[3]/div[6]/button[1]', 'role': 'button'}],
        'view_all_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View all'}, {'strategy': 'text', 'value': 'View all', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_3_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[3]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'ask_stewie_about_assets_rules_domains': [{'strategy': 'placeholder', 'value': 'Ask Stewie about assets, rules, domains...', 'role': 'textbox'}],
        'view_full_chat_history': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View full chat history'}, {'strategy': 'text', 'value': 'View full chat history', 'role': 'button'}],
        'ask': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask'}, {'strategy': 'text', 'value': 'Ask', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_3_div_2_div_1_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[3]/div[2]/div[1]/div[1]/button[1]', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_2_div_1_div_1_div_1_div_3_section_3_div_2_div_2_div_1_button_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/section[3]/div[2]/div[2]/div[1]/button[1]', 'role': 'button'}],
        'view_all_3': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'View all'}, {'strategy': 'text', 'value': 'View all', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to Home section"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie dialog"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Open Data Catalog section"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection section"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Open Data Quality section"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines section"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Open Agent Management section"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security section"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications section"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Logout from application"""
        self.click('logout')

    def click_refresh(self) -> None:
        """Refresh page content"""
        self.click('refresh')

    def fill_search_assets(self, value: str) -> None:
        """Fill asset search textbox"""
        self.fill('search_assets_terms_rules_type_for_suggestions', value)

    def click_find_pii_risks(self) -> None:
        """Find PII risks"""
        self.click('find_pii_risks')

    def click_show_failing_rule_sets(self) -> None:
        """Show failing rule sets"""
        self.click('show_failing_rule_sets')

    def click_pending_certification(self) -> None:
        """Show pending certifications"""
        self.click('pending_certification')

    def click_view_all(self) -> None:
        """View all items"""
        self.click('view_all')

    def fill_ask_stewie_about_assets(self, value: str) -> None:
        """Fill Ask Stewie textbox"""
        self.fill('ask_stewie_about_assets_rules_domains', value)

    def click_view_full_chat_history(self) -> None:
        """View full chat history"""
        self.click('view_full_chat_history')

    def click_ask(self) -> None:
        """Submit Ask Stewie question"""
        self.click('ask')

    def click_close_sidebar(self) -> None:
        """Close sidebar menu"""
        self.click('close_sidebar')
