"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/login.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class LoginPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/login"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'sign_in_with_microsoft': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Sign in with Microsoft'}, {'strategy': 'text', 'value': 'Sign in with Microsoft', 'role': 'button'}],
        'html_1_body_1_div_1_div_1_div_2_div_1_label_1_input_1': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/label[1]/input[1]', 'role': 'textbox'}],
        'terms_of_service': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Terms of Service'}, {'strategy': 'text', 'value': 'Terms of Service', 'role': 'button'}],
        'privacy_policy': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Privacy Policy'}, {'strategy': 'text', 'value': 'Privacy Policy', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        self.page.goto(self.URL)

    def click_sign_in_with_microsoft(self) -> None:
        """Click the 'Sign in with Microsoft' button."""
        self.locate('sign_in_with_microsoft').click()

    def fill_email(self, value: str) -> None:
        """Fill the email input field."""
        self.locate('html_1_body_1_div_1_div_1_div_2_div_1_label_1_input_1').fill(value)

    def click_terms_of_service(self) -> None:
        """Click the 'Terms of Service' button."""
        self.locate('terms_of_service').click()

    def click_privacy_policy(self) -> None:
        """Click the 'Privacy Policy' button."""
        self.locate('privacy_policy').click()
