"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/security.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class SecurityPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/security"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'request_access': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Request Access'}, {'strategy': 'text', 'value': 'Request Access', 'role': 'button'}],
        'admin_full_system_access_can_manage_users_and_roles': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Admin Full system access, can manage users and roles'}, {'strategy': 'text', 'value': 'Admin Full system access, can manage users and roles', 'role': 'button'}],
        'data_owner_can_edit_and_manage_data_assets_they_own': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Owner Can edit and manage data assets they own'}, {'strategy': 'text', 'value': 'Data Owner Can edit and manage data assets they own', 'role': 'button'}],
        'data_steward_can_manage_data_quality_and_governance': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Steward Can manage data quality and governance'}, {'strategy': 'text', 'value': 'Data Steward Can manage data quality and governance', 'role': 'button'}],
        'reader_read_only_access_to_data_catalog_and_assets': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Reader Read-only access to data catalog and assets'}, {'strategy': 'text', 'value': 'Reader Read-only access to data catalog and assets', 'role': 'button'}],
        'superuser_super_user_with_elevated_permissions': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'SuperUser Super user with elevated permissions'}, {'strategy': 'text', 'value': 'SuperUser Super user with elevated permissions', 'role': 'button'}],
        'reason_for_request': [{'strategy': 'label', 'value': 'Reason for Request *', 'role': 'textbox'}, {'strategy': 'placeholder', 'value': 'Please explain why you need this role...', 'role': 'textbox'}, {'strategy': 'css', 'value': '#reason', 'role': 'textbox'}],
        'submit_request': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Submit Request'}, {'strategy': 'text', 'value': 'Submit Request', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to Home"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Open Data Catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Open Data Quality"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Open Agent Management"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Logout user"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """Close sidebar"""
        self.click('close_sidebar')

    def click_request_access(self) -> None:
        """Request access"""
        self.click('request_access')

    def click_admin_access(self) -> None:
        """Select Admin role"""
        self.click('admin_full_system_access_can_manage_users_and_roles')

    def click_data_owner_access(self) -> None:
        """Select Data Owner role"""
        self.click('data_owner_can_edit_and_manage_data_assets_they_own')

    def click_data_steward_access(self) -> None:
        """Select Data Steward role"""
        self.click('data_steward_can_manage_data_quality_and_governance')

    def click_reader_access(self) -> None:
        """Select Reader role"""
        self.click('reader_read_only_access_to_data_catalog_and_assets')

    def click_superuser_access(self) -> None:
        """Select SuperUser role"""
        self.click('superuser_super_user_with_elevated_permissions')

    def fill_reason_for_request(self, value: str) -> None:
        """Fill reason for access request"""
        self.fill('reason_for_request', value)

    def click_submit_request(self) -> None:
        """Submit access request"""
        self.click('submit_request')
