"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/sources.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class SourcesPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/sources"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'create_new_pipeline': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Create New Pipeline'}, {'strategy': 'text', 'value': 'Create New Pipeline', 'role': 'button'}],
        'dqm_adhoc_validation_created_9_30_2025_12_19_36_pm_id_6aea95f5_af40_461d_936d_4ecc7937cb35': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'DQM_AdHoc_Validation\nCreated: 9/30/2025, 12:19:36 PM\nID: 6AEA95F5-AF40-461D-936D-4ECC7937CB35'}, {'strategy': 'text', 'value': 'DQM_AdHoc_Validation\nCreated: 9/30/2025, 12:19:36 PM\nID: 6AEA95F5-AF40-461D-936D-4ECC7937CB35', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_1_div_2_div_1_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[2]', 'role': 'button'}],
        'dqm_transaction_validation_created_10_1_2025_2_06_08_pm_id_53728987_f81f_4025_be68_83aacafbfdd8': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'DQM_Transaction_Validation\nCreated: 10/1/2025, 2:06:08 PM\nID: 53728987-F81F-4025-BE68-83AACAFBFDD8'}, {'strategy': 'text', 'value': 'DQM_Transaction_Validation\nCreated: 10/1/2025, 2:06:08 PM\nID: 53728987-F81F-4025-BE68-83AACAFBFDD8', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_1_div_2_div_2_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/button[2]', 'role': 'button'}],
        'dqm_account_validation_created_10_1_2025_5_43_52_pm_id_68c70f1f_3af4_4fc5_95af_bae611dd91fc': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'DQM_Account_Validation\nCreated: 10/1/2025, 5:43:52 PM\nID: 68C70F1F-3AF4-4FC5-95AF-BAE611DD91FC'}, {'strategy': 'text', 'value': 'DQM_Account_Validation\nCreated: 10/1/2025, 5:43:52 PM\nID: 68C70F1F-3AF4-4FC5-95AF-BAE611DD91FC', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_1_div_2_div_3_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/button[2]', 'role': 'button'}],
        'dqm_monthly_run_created_10_3_2025_4_13_46_pm_id_df848b30_780e_4af2_aa58_3a477433ac62': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'DQM_Monthly_Run\nCreated: 10/3/2025, 4:13:46 PM\nID: DF848B30-780E-4AF2-AA58-3A477433AC62'}, {'strategy': 'text', 'value': 'DQM_Monthly_Run\nCreated: 10/3/2025, 4:13:46 PM\nID: DF848B30-780E-4AF2-AA58-3A477433AC62', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_1_div_2_div_4_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/button[2]', 'role': 'button'}],
        'dqm_weekly_run_created_12_16_2025_5_51_44_pm_id_c2f26dae_9e5c_40a2_82e3_0d43a575ed9a': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'DQM_Weekly_Run\nCreated: 12/16/2025, 5:51:44 PM\nID: C2F26DAE-9E5C-40A2-82E3-0D43A575ED9A'}, {'strategy': 'text', 'value': 'DQM_Weekly_Run\nCreated: 12/16/2025, 5:51:44 PM\nID: C2F26DAE-9E5C-40A2-82E3-0D43A575ED9A', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_1_div_2_div_5_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[5]/button[2]', 'role': 'button'}],
        'save_pipeline': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Save Pipeline'}, {'strategy': 'text', 'value': 'Save Pipeline', 'role': 'button'}],
        'run_pipeline': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Run Pipeline'}, {'strategy': 'text', 'value': 'Run Pipeline', 'role': 'button'}],
        'add_nodes_to_simulate': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Add nodes to simulate'}, {'strategy': 'text', 'value': 'Add nodes to simulate', 'role': 'button'}],
        'delete_selected': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Delete Selected'}, {'strategy': 'text', 'value': 'Delete Selected', 'role': 'button'}],
        'auto_layout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Auto Layout'}, {'strategy': 'text', 'value': 'Auto Layout', 'role': 'button'}],
        'zoom_in': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'zoom in'}, {'strategy': 'label', 'value': 'zoom in', 'role': 'button', 'name': 'zoom in'}, {'strategy': 'text', 'value': 'zoom in', 'role': 'button'}],
        'zoom_out': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'zoom out'}, {'strategy': 'label', 'value': 'zoom out', 'role': 'button', 'name': 'zoom out'}, {'strategy': 'text', 'value': 'zoom out', 'role': 'button'}],
        'fit_view': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'fit view'}, {'strategy': 'label', 'value': 'fit view', 'role': 'button', 'name': 'fit view'}, {'strategy': 'text', 'value': 'fit view', 'role': 'button'}],
        'toggle_interactivity': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'toggle interactivity'}, {'strategy': 'label', 'value': 'toggle interactivity', 'role': 'button', 'name': 'toggle interactivity'}, {'strategy': 'text', 'value': 'toggle interactivity', 'role': 'button'}],
        'runs_logs': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Runs & Logs'}, {'strategy': 'text', 'value': 'Runs & Logs', 'role': 'button'}],
        'agents': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agents'}, {'strategy': 'text', 'value': 'Agents', 'role': 'button'}],
        'configuration': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Configuration'}, {'strategy': 'text', 'value': 'Configuration', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to Home"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Open Data Catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Open Data Quality"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Open Agent Management"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Logout user"""
        self.click('logout')

    def click_create_new_pipeline(self) -> None:
        """Create new pipeline"""
        self.click('create_new_pipeline')

    def click_save_pipeline(self) -> None:
        """Save current pipeline"""
        self.click('save_pipeline')

    def click_run_pipeline(self) -> None:
        """Run current pipeline"""
        self.click('run_pipeline')

    def click_add_nodes_to_simulate(self) -> None:
        """Add nodes to simulation"""
        self.click('add_nodes_to_simulate')

    def click_delete_selected(self) -> None:
        """Delete selected items"""
        self.click('delete_selected')

    def click_auto_layout(self) -> None:
        """Auto layout pipeline"""
        self.click('auto_layout')

    def click_zoom_in(self) -> None:
        """Zoom in pipeline view"""
        self.click('zoom_in')

    def click_zoom_out(self) -> None:
        """Zoom out pipeline view"""
        self.click('zoom_out')

    def click_fit_view(self) -> None:
        """Fit pipeline to view"""
        self.click('fit_view')

    def click_toggle_interactivity(self) -> None:
        """Toggle pipeline interactivity"""
        self.click('toggle_interactivity')
