"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/source-connection.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class SourceConnectionPage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/source-connection"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'add_new_source': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Add New Source'}, {'strategy': 'text', 'value': 'Add New Source', 'role': 'button'}],
        'wh_cv_analytics_dev_gyg7m327skcupkcukehzbhxfme_tfcq25t4tyxeznlthxasjz7vzq_datawarehouse_fabric_microsoft_com': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'WH_CV_ANALYTICS_DEV • gyg7m327skcupkcukehzbhxfme-tfcq25t4tyxeznlthxasjz7vzq.datawarehouse.fabric.microsoft.com'}, {'strategy': 'text', 'value': 'WH_CV_ANALYTICS_DEV • gyg7m327skcupkcukehzbhxfme-tfcq25t4tyxeznlthxasjz7vzq.datawarehouse.fabric.microsoft.com', 'role': 'button'}],
        'bcdeunhemp3bpu9vsrxs_bcdeunhemp3bpu9vsrxs_mysql_services_clever_cloud_com': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'bcdeunhemp3bpu9vsrxs • bcdeunhemp3bpu9vsrxs-mysql.services.clever-cloud.com'}, {'strategy': 'text', 'value': 'bcdeunhemp3bpu9vsrxs • bcdeunhemp3bpu9vsrxs-mysql.services.clever-cloud.com', 'role': 'button'}],
        'catalog_test_db_tesgpqj_nq15615': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'CATALOG_TEST_DB • tesgpqj-nq15615'}, {'strategy': 'text', 'value': 'CATALOG_TEST_DB • tesgpqj-nq15615', 'role': 'button'}],
        'sqldb_decoe_internal_sql_decoe_internal_database_windows_net': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'sqldb-decoe-internal • sql-decoe-internal.database.windows.net'}, {'strategy': 'text', 'value': 'sqldb-decoe-internal • sql-decoe-internal.database.windows.net', 'role': 'button'}],
        'xe_sbsqld73': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'XE • SBSQLD73'}, {'strategy': 'text', 'value': 'XE • SBSQLD73', 'role': 'button'}],
        'wh_cv_analytics_dev_gyg7m327skcupkcukehzbhxfme_tfcq25t4tyxeznlthxasjz7vzq_datawarehouse_fabric_microsoft_com_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'WH_CV_ANALYTICS_DEV • gyg7m327skcupkcukehzbhxfme-tfcq25t4tyxeznlthxasjz7vzq.datawarehouse.fabric.microsoft.com'}, {'strategy': 'text', 'value': 'WH_CV_ANALYTICS_DEV • gyg7m327skcupkcukehzbhxfme-tfcq25t4tyxeznlthxasjz7vzq.datawarehouse.fabric.microsoft.com', 'role': 'button'}],
        'oracle_database': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Oracle Database'}, {'strategy': 'text', 'value': 'Oracle Database', 'role': 'button'}],
        'mysql': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'MySQL'}, {'strategy': 'text', 'value': 'MySQL', 'role': 'button'}],
        'snowflake': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Snowflake'}, {'strategy': 'text', 'value': 'Snowflake', 'role': 'button'}],
        'sql_server_azure_sql': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'SQL Server / Azure SQL'}, {'strategy': 'text', 'value': 'SQL Server / Azure SQL', 'role': 'button'}],
        'microsoft_fabric': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Microsoft Fabric'}, {'strategy': 'text', 'value': 'Microsoft Fabric', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to Home"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Go to Data Catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Go to Data Quality"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Go to Agent Management"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Logout user"""
        self.click('logout')

    def click_close_sidebar(self) -> None:
        """Close sidebar menu"""
        self.click('close_sidebar')

    def click_add_new_source(self) -> None:
        """Add a new source"""
        self.click('add_new_source')

    def click_wh_cv_analytics_dev(self) -> None:
        """Select WH_CV_ANALYTICS_DEV source"""
        self.click('wh_cv_analytics_dev_gyg7m327skcupkcukehzbhxfme_tfcq25t4tyxeznlthxasjz7vzq_datawarehouse_fabric_microsoft_com')

    def click_mysql_clever_cloud(self) -> None:
        """Select MySQL Clever Cloud source"""
        self.click('bcdeunhemp3bpu9vsrxs_bcdeunhemp3bpu9vsrxs_mysql_services_clever_cloud_com')

    def click_catalog_test_db(self) -> None:
        """Select CATALOG_TEST_DB source"""
        self.click('catalog_test_db_tesgpqj_nq15615')

    def click_sqldb_decoe_internal(self) -> None:
        """Select SQLDB DecoE Internal source"""
        self.click('sqldb_decoe_internal_sql_decoe_internal_database_windows_net')

    def click_xe_sbsqld73(self) -> None:
        """Select XE SBSQLD73 source"""
        self.click('xe_sbsqld73')

    def click_wh_cv_analytics_dev_2(self) -> None:
        """Select WH_CV_ANALYTICS_DEV source 2"""
        self.click('wh_cv_analytics_dev_gyg7m327skcupkcukehzbhxfme_tfcq25t4tyxeznlthxasjz7vzq_datawarehouse_fabric_microsoft_com_2')

    def click_oracle_database(self) -> None:
        """Select Oracle Database"""
        self.click('oracle_database')

    def click_mysql(self) -> None:
        """Select MySQL"""
        self.click('mysql')
