"""Generated by autocoder for https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/stewie.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec


class StewiePage(BasePage):
    URL = "https://aps-aitl-frontend-bja4eebjg6cyguea.northcentralus-01.azurewebsites.net/stewie"
    SELECTORS: dict[str, list[SelectorSpec]] = {
        'home': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Home'}, {'strategy': 'label', 'value': 'Home', 'role': 'button', 'name': 'Home'}, {'strategy': 'text', 'value': 'Home', 'role': 'button'}],
        'ask_stewie': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'label', 'value': 'Ask Stewie', 'role': 'button', 'name': 'Ask Stewie'}, {'strategy': 'text', 'value': 'Ask Stewie', 'role': 'button'}],
        'data_catalog': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'label', 'value': 'Data Catalog', 'role': 'button', 'name': 'Data Catalog'}, {'strategy': 'text', 'value': 'Data Catalog', 'role': 'button'}],
        'source_connection': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'label', 'value': 'Source Connection', 'role': 'button', 'name': 'Source Connection'}, {'strategy': 'text', 'value': 'Source Connection', 'role': 'button'}],
        'data_quality': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'label', 'value': 'Data Quality', 'role': 'button', 'name': 'Data Quality'}, {'strategy': 'text', 'value': 'Data Quality', 'role': 'button'}],
        'agent_pipelines': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'label', 'value': 'Agent Pipelines', 'role': 'button', 'name': 'Agent Pipelines'}, {'strategy': 'text', 'value': 'Agent Pipelines', 'role': 'button'}],
        'agent_management': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'label', 'value': 'Agent Management', 'role': 'button', 'name': 'Agent Management'}, {'strategy': 'text', 'value': 'Agent Management', 'role': 'button'}],
        'security': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Security'}, {'strategy': 'label', 'value': 'Security', 'role': 'button', 'name': 'Security'}, {'strategy': 'text', 'value': 'Security', 'role': 'button'}],
        'notifications': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'label', 'value': 'Notifications', 'role': 'button', 'name': 'Notifications'}, {'strategy': 'text', 'value': 'Notifications', 'role': 'button'}],
        'logout': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Logout'}, {'strategy': 'label', 'value': 'Logout', 'role': 'button', 'name': 'Logout'}, {'strategy': 'text', 'value': 'Logout', 'role': 'button'}],
        'close_sidebar': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'label', 'value': 'Close sidebar', 'role': 'button', 'name': 'Close sidebar'}, {'strategy': 'text', 'value': 'Close sidebar', 'role': 'button'}],
        'new_conversation': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'New Conversation'}, {'strategy': 'text', 'value': 'New Conversation', 'role': 'button'}],
        'all': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'All'}, {'strategy': 'text', 'value': 'All', 'role': 'button'}],
        'pinned': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Pinned'}, {'strategy': 'text', 'value': 'Pinned', 'role': 'button'}],
        'search': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Search'}, {'strategy': 'label', 'value': 'Search', 'role': 'button', 'name': 'Search'}, {'strategy': 'text', 'value': 'Search', 'role': 'button'}],
        'list_all_the_finance_domain_assets': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'List all the finance domain assets'}, {'strategy': 'text', 'value': 'List all the finance domain assets', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_2_div_2_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[2]/button[2]', 'role': 'button'}],
        'list_all_the_financial_assets': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'List all the financial assets'}, {'strategy': 'text', 'value': 'List all the financial assets', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_2_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/button[2]', 'role': 'button'}],
        'list_all_the_financial_assets_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'List all the financial assets'}, {'strategy': 'text', 'value': 'List all the financial assets', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_3_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[3]/button[2]', 'role': 'button'}],
        'list_all_the_financial_assets_3': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'List all the financial assets'}, {'strategy': 'text', 'value': 'List all the financial assets', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_4_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[4]/button[2]', 'role': 'button'}],
        'list_all_the_financial_assets_4': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'List all the financial assets'}, {'strategy': 'text', 'value': 'List all the financial assets', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_5_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[5]/button[2]', 'role': 'button'}],
        'list_of_all_assets_within_finance_domain': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'List of all assets within Finance domain'}, {'strategy': 'text', 'value': 'List of all assets within Finance domain', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_6_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[6]/button[2]', 'role': 'button'}],
        'who_is_the_data_owner_and_data_steward_for_account_type_table': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'who is the data owner and data steward for @ACCOUNT_TYPE Table'}, {'strategy': 'text', 'value': 'who is the data owner and data steward for @ACCOUNT_TYPE Table', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_7_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[7]/button[2]', 'role': 'button'}],
        'avishi_raj_crowe_com': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Avishi.Raj@crowe.com'}, {'strategy': 'text', 'value': 'Avishi.Raj@crowe.com', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_8_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[8]/button[2]', 'role': 'button'}],
        'avishi_raj_crowe_com_2': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Avishi.Raj@crowe.com'}, {'strategy': 'text', 'value': 'Avishi.Raj@crowe.com', 'role': 'button'}],
        'html_1_body_1_div_1_div_2_div_2_div_1_div_1_div_1_div_2_div_2_div_3_div_9_button_2': [{'strategy': 'xpath', 'value': '/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[9]/button[2]', 'role': 'button'}],
        'load_more': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Load more...'}, {'strategy': 'text', 'value': 'Load more...', 'role': 'button'}],
        'which_tables_contain_pii_data': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Which tables contain PII data?'}, {'strategy': 'text', 'value': '• Which tables contain PII data?', 'role': 'button'}],
        'show_me_data_quality_results_for_customer_table': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Show me Data Quality results for @Customer Table?'}, {'strategy': 'text', 'value': '• Show me Data Quality results for @Customer Table?', 'role': 'button'}],
        'list_all_assets_within_finance_domain': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• List all assets within Finance domain.'}, {'strategy': 'text', 'value': '• List all assets within Finance domain.', 'role': 'button'}],
        'tell_me_tables_with_ach_transaction_details': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Tell me tables with ACH transaction details.'}, {'strategy': 'text', 'value': '• Tell me tables with ACH transaction details.', 'role': 'button'}],
        'tell_me_what_values_do_we_have_for_customer_type': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Tell me what values do we have for Customer Type.'}, {'strategy': 'text', 'value': '• Tell me what values do we have for Customer Type.', 'role': 'button'}],
        'list_datasets_that_reference_the_swift_code': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• List datasets that reference the SWIFT code.'}, {'strategy': 'text', 'value': '• List datasets that reference the SWIFT code.', 'role': 'button'}],
        'which_datasets_am_i_responsible_for': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Which datasets am I responsible for?'}, {'strategy': 'text', 'value': '• Which datasets am I responsible for?', 'role': 'button'}],
        'summarize_the_data_quality_status_of_tables_i_own': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Summarize the data quality status of tables I own.'}, {'strategy': 'text', 'value': '• Summarize the data quality status of tables I own.', 'role': 'button'}],
        'show_me_datasets_i_need_to_update_classification_tag': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': '• Show me datasets I need to update Classification tag.'}, {'strategy': 'text', 'value': '• Show me datasets I need to update Classification tag.', 'role': 'button'}],
        'ask_stewie_type_for_asset_suggestions': [{'strategy': 'placeholder', 'value': 'Ask Stewie... (Type @ for asset suggestions)', 'role': 'textbox'}],
        'choose_role': [{'strategy': 'role_name', 'value': 'combobox', 'role': 'combobox', 'name': 'Choose role'}, {'strategy': 'label', 'value': 'Choose role', 'role': 'combobox', 'name': 'Choose role'}],
        'send': [{'strategy': 'role_name', 'value': 'button', 'role': 'button', 'name': 'Send'}, {'strategy': 'label', 'value': 'Send', 'role': 'button', 'name': 'Send'}, {'strategy': 'text', 'value': 'Send', 'role': 'button'}],
    }

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")

    def click_home(self) -> None:
        """Navigate to home"""
        self.click('home')

    def click_ask_stewie(self) -> None:
        """Open Ask Stewie"""
        self.click('ask_stewie')

    def click_data_catalog(self) -> None:
        """Open Data Catalog"""
        self.click('data_catalog')

    def click_source_connection(self) -> None:
        """Open Source Connection"""
        self.click('source_connection')

    def click_data_quality(self) -> None:
        """Open Data Quality"""
        self.click('data_quality')

    def click_agent_pipelines(self) -> None:
        """Open Agent Pipelines"""
        self.click('agent_pipelines')

    def click_agent_management(self) -> None:
        """Open Agent Management"""
        self.click('agent_management')

    def click_security(self) -> None:
        """Open Security"""
        self.click('security')

    def click_notifications(self) -> None:
        """Open Notifications"""
        self.click('notifications')

    def click_logout(self) -> None:
        """Logout user"""
        self.click('logout')

    def click_new_conversation(self) -> None:
        """Start new conversation"""
        self.click('new_conversation')

    def fill_ask_stewie_type_for_asset_suggestions(self, value: str) -> None:
        """Fill Stewie question"""
        self.fill('ask_stewie_type_for_asset_suggestions', value)

    def select_choose_role(self, value: str) -> None:
        """Select user role"""
        self.select('choose_role', value)

    def click_send(self) -> None:
        """Send Stewie question"""
        self.click('send')

    def click_close_sidebar(self) -> None:
        """Close sidebar"""
        self.click('close_sidebar')

    def click_search(self) -> None:
        """Search assets"""
        self.click('search')

    def click_load_more(self) -> None:
        """Load more results"""
        self.click('load_more')

    def click_list_all_the_finance_domain_assets(self) -> None:
        """List finance domain assets"""
        self.click('list_all_the_finance_domain_assets')

    def click_list_of_all_assets_within_finance_domain(self) -> None:
        """List all assets in finance domain"""
        self.click('list_of_all_assets_within_finance_domain')

    def click_show_me_data_quality_results_for_customer_table(self) -> None:
        """Show data quality for customer table"""
        self.click('show_me_data_quality_results_for_customer_table')
