"""Render a pure-Playwright pytest module from a :class:`PlaywrightScriptPlan`.

Output shape (one file per URL) goes to ``tests/playwright/test_<slug>.py``:

    \"\"\"Generated Playwright tests for <Feature>.\"\"\"

    from __future__ import annotations

    import pytest
    from playwright.sync_api import Page, expect

    from tests.pages.<pom_module> import <PomClass>


    @pytest.fixture
    def pom(page: Page) -> <PomClass>:
        return <PomClass>(page)


    @pytest.mark.smoke
    def test_<slug>(pom: <PomClass>) -> None:
        \"\"\"<scenario title>\"\"\"
        pom.navigate()
        pom.click_login()
        expect(pom.locate("dashboard-heading")).to_be_visible()

The renderer performs a final AST parse on the assembled source and
substitutes a safe ``pass`` body for any function whose statement list
did not pass validation, so the file always parses even if the LLM
returned a few bad entries. Statements flagged as invalid are recorded
as ``raise NotImplementedError(...)`` so the heal stage can pick them
up later.
"""

from __future__ import annotations

import ast

from autocoder.heal.validator import validate_body
from autocoder.models import Element, PlaywrightScriptPlan, PlaywrightTest


_HEADER = '''"""Generated Playwright tests for {feature_title!r}.

Auto-generated by autocoder. Do not hand-edit — rerun
`autocoder generate` or use `autocoder heal` to patch failing tests.
"""

from __future__ import annotations

import pytest
from playwright.sync_api import Page, expect

from tests.pages.{pom_module} import {pom_class}


@pytest.fixture
def {pom_fixture}(page: Page) -> {pom_class}:
    return {pom_class}(page)
'''


_TEST_TPL = '''

@pytest.mark.{tier}{extra_marks}
def {test_name}({pom_fixture}: {pom_class}) -> None:
    """{doc}"""
{body}
'''


def _format_marks(tags: list[str], tier: str) -> str:
    """Return additional ``@pytest.mark.X`` decorator lines after the tier.

    Keeps one decorator per line so the output is greppable.
    """
    extras = [t for t in tags if t and t != tier]
    if not extras:
        return ""
    return "\n" + "\n".join(f"@pytest.mark.{t}" for t in extras)


def _escape_docstring(text: str) -> str:
    # Single-line docstrings only; collapse triple quotes to avoid breaking the block.
    return text.replace('"""', "'''").replace("\n", " ").strip()


def _render_body(
    statements: list[str],
    *,
    pom_fixture: str,
    pom_method_names: set[str],
    element_ids: set[str],
) -> tuple[list[str], list[str]]:
    """Return ``(rendered_lines, issues)`` for a single test.

    Each statement is validated in isolation via :func:`validate_body`
    (single-statement mode); invalid ones become
    ``raise NotImplementedError(...)`` so the heal stage can revise them.
    """
    lines: list[str] = []
    issues: list[str] = []
    for raw in statements:
        stmt = (raw or "").strip()
        if not stmt:
            continue
        if stmt == "pass":
            lines.append("    pass")
            continue
        cleaned, errs = validate_body(
            stmt,
            fixture_name=pom_fixture,
            pom_method_names=pom_method_names,
            element_ids=element_ids,
            max_statements=1,
        )
        if errs:
            issues.append(f"{stmt!r}: {'; '.join(errs)}")
            escaped = stmt.replace('"', '\\"')
            lines.append(
                f'    raise NotImplementedError("Implement step: {escaped}")'
            )
            continue
        lines.append(f"    {cleaned}")
    if not lines:
        lines.append("    pass")
    return lines, issues


def render_playwright_script(
    plan: PlaywrightScriptPlan,
    *,
    feature_title: str,
    pom_method_names: set[str],
    elements: list[Element],
) -> tuple[str, int]:
    """Return ``(source, placeholder_count)``.

    ``placeholder_count`` is the number of statements the validator
    rejected and therefore rendered as ``NotImplementedError`` stubs.
    The orchestrator uses it as the quality gate signal: a non-zero
    value promotes the node to ``NEEDS_IMPLEMENTATION`` so the heal
    stage is triggered for it.
    """
    element_ids = {e.id for e in elements}
    parts: list[str] = [
        _HEADER.format(
            feature_title=feature_title,
            pom_module=plan.pom_module,
            pom_class=plan.pom_class,
            pom_fixture=plan.pom_fixture,
        )
    ]
    placeholder_count = 0
    for test in plan.tests:
        body_lines, issues = _render_body(
            test.statements,
            pom_fixture=plan.pom_fixture,
            pom_method_names=pom_method_names,
            element_ids=element_ids,
        )
        placeholder_count += sum(1 for ln in body_lines if "NotImplementedError" in ln)
        parts.append(
            _TEST_TPL.format(
                tier=test.tier,
                extra_marks=_format_marks(test.tags, test.tier),
                test_name=test.name,
                pom_fixture=plan.pom_fixture,
                pom_class=plan.pom_class,
                doc=_escape_docstring(test.scenario_title),
                body="\n".join(body_lines),
            )
        )
    source = "".join(parts)
    # Sanity-check: never write a file that fails to parse. If we ever
    # produce something that does not parse, the renderer is buggy —
    # surface with a clear error instead of silently writing junk.
    ast.parse(source)
    return source, placeholder_count
