"""Render Page Object Model files.

Each generated POM:

* extends ``tests/pages/base_page.py`` (provides the self-healing
  locator helper).
* exposes one method per :class:`POMMethod` in the plan.
* keeps element-id -> selector maps as class-level constants so they
  are easy to diff between reruns.

The renderer never uses the LLM — it only formats strings around the
already-validated plan + extraction.
"""

from __future__ import annotations

from urllib.parse import urlparse

from autocoder.models import (
    Element,
    PageExtraction,
    POMPlan,
    SelectorStrategy,
    StableSelector,
)


_HEADER = '''"""Generated by autocoder for {url}.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests import settings
from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec
'''


_CLASS_TPL = '''

class {class_name}(BasePage):
    # Path component only — the absolute URL is built at runtime from
    # ``settings.BASE_URL`` so the same POM targets dev / staging / prod
    # without regeneration. The extraction URL captured at generation
    # time was: {url}
    PATH = "{path}"
    SELECTORS: dict[str, list[SelectorSpec]] = {selectors_dict}

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    @property
    def URL(self) -> str:
        """Absolute URL for this page, joined against ``settings.BASE_URL``.

        Raises if ``BASE_URL`` is empty so a missing ``.env`` entry
        fails loudly instead of silently hitting ``about:blank`` or
        whatever Playwright does with a bare path.
        """
        base = (settings.BASE_URL or "").rstrip("/")
        if not base:
            raise RuntimeError(
                "BASE_URL is not set in .env — add it so tests target "
                "your environment (dev / staging / prod)."
            )
        return base + self.PATH

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")
'''


def _url_to_path(url: str) -> str:
    """Return the path+query+fragment portion of ``url``, defaulting to ``/``.

    Used so the generated POM stores only the env-agnostic path; the
    host comes from ``settings.BASE_URL`` at runtime.
    """
    parsed = urlparse(url)
    path = parsed.path or "/"
    if parsed.query:
        path = f"{path}?{parsed.query}"
    if parsed.fragment:
        path = f"{path}#{parsed.fragment}"
    return path


_METHOD_TPL = '''
    def {name}(self{params}) -> None:
        """{intent}"""
        {body}
'''


def _selector_to_dict(sel: StableSelector) -> dict:
    out: dict = {"strategy": sel.strategy.value, "value": sel.value}
    if sel.role:
        out["role"] = sel.role
    if sel.name:
        out["name"] = sel.name
    if sel.nth is not None:
        out["nth"] = sel.nth
    return out


def _element_to_specs(element: Element) -> list[dict]:
    return [_selector_to_dict(element.selector), *(_selector_to_dict(s) for s in element.fallbacks)]


def _format_selector_dict(elements: list[Element]) -> str:
    rows = []
    for e in elements:
        specs = _element_to_specs(e)
        rows.append(f"        {e.id!r}: {specs!r},")
    if not rows:
        return "{}"
    return "{\n" + "\n".join(rows) + "\n    }"


def _build_method_body(method, element: Element | None) -> str:
    action = method.action
    if action == "navigate":
        return "self.navigate()"
    if element is None:
        return "raise RuntimeError('element missing')"

    # Click / check / fill / select go through the self-healing
    # wrappers on ``BasePage`` so disabled-until-consent buttons are
    # unblocked automatically at test time (see
    # ``tests/pages/base_page.py``). The runtime self-heal is a safety
    # net for two common failure modes: LLM-ordered scenario steps
    # that trigger a gated button before the consent checkbox, and
    # captured DOMs that drift slightly between extraction and test.
    if action == "click":
        return f"self.click({element.id!r})"
    if action == "fill":
        arg = method.args[0] if method.args else "value"
        return f"self.fill({element.id!r}, {arg})"
    if action == "select":
        arg = method.args[0] if method.args else "value"
        return f"self.select({element.id!r}, {arg})"
    if action == "check":
        return f"self.check({element.id!r})"

    locator = f"self.locate({element.id!r})"
    if action == "wait":
        return f"{locator}.wait_for(state='visible')"
    if action == "expect_visible":
        return f"expect({locator}).to_be_visible()"
    if action == "expect_text":
        arg = method.args[0] if method.args else "value"
        return f"expect({locator}).to_contain_text({arg})"
    if action == "press_enter":
        # Keyboard-submit path for search/chat/form inputs whose
        # submission is Enter-triggered (no adjacent submit button).
        # Raw ``locator.press`` — the consent-checkbox heal path in
        # BasePage only wraps click/check/fill/select; press has no
        # equivalent failure mode that benefits from the heal loop.
        return f"{locator}.press('Enter')"
    return "pass"


def _build_method_params(method) -> str:
    if method.action in {"fill", "select", "expect_text"}:
        return ", " + ", ".join(f"{a}: str" for a in (method.args or ["value"]))
    return ""


def render_pom(plan: POMPlan, extraction: PageExtraction) -> str:
    by_id = {e.id: e for e in extraction.elements}
    selectors_dict = _format_selector_dict(extraction.elements)

    parts = [_HEADER.format(url=extraction.final_url)]
    parts.append(
        _CLASS_TPL.format(
            class_name=plan.class_name,
            url=extraction.final_url,
            path=_url_to_path(extraction.final_url),
            selectors_dict=selectors_dict,
        )
    )

    for method in plan.methods:
        element = by_id.get(method.element_id)
        body = _build_method_body(method, element)
        parts.append(
            _METHOD_TPL.format(
                name=method.name,
                params=_build_method_params(method),
                intent=method.intent.replace('"""', "'''"),
                body=body,
            )
        )

    return "".join(parts)
