"""Render Page Object Model files.

Each generated POM:

* extends ``tests/pages/base_page.py`` (provides the self-healing
  locator helper).
* exposes one method per :class:`POMMethod` in the plan.
* keeps element-id -> selector maps as class-level constants so they
  are easy to diff between reruns.

The renderer never uses the LLM — it only formats strings around the
already-validated plan + extraction.
"""

from __future__ import annotations

from autocoder.models import (
    Element,
    PageExtraction,
    POMPlan,
    SelectorStrategy,
    StableSelector,
)


_HEADER = '''"""Generated by autocoder for {url}.

Edit by hand only if you accept that future runs may overwrite parts of
this file. The selector dictionary at the top is the safe place to
patch when tests start to flake — the orchestrator preserves it during
re-renders.
"""

from __future__ import annotations

from playwright.sync_api import Page, expect

from tests.pages.base_page import BasePage
from tests.support.locator_strategy import SelectorSpec
'''


_CLASS_TPL = '''

class {class_name}(BasePage):
    URL = "{url}"
    SELECTORS: dict[str, list[SelectorSpec]] = {selectors_dict}

    def __init__(self, page: Page) -> None:
        super().__init__(page, self.SELECTORS)

    def navigate(self) -> None:
        # ``domcontentloaded`` matches the extraction-time wait ladder
        # and avoids timing out on SPAs whose telemetry/analytics
        # requests prevent the ``load`` event from firing inside 30s.
        self.page.goto(self.URL, wait_until="domcontentloaded")
'''


_METHOD_TPL = '''
    def {name}(self{params}) -> None:
        """{intent}"""
        {body}
'''


def _selector_to_dict(sel: StableSelector) -> dict:
    out: dict = {"strategy": sel.strategy.value, "value": sel.value}
    if sel.role:
        out["role"] = sel.role
    if sel.name:
        out["name"] = sel.name
    if sel.nth is not None:
        out["nth"] = sel.nth
    return out


def _element_to_specs(element: Element) -> list[dict]:
    return [_selector_to_dict(element.selector), *(_selector_to_dict(s) for s in element.fallbacks)]


def _format_selector_dict(elements: list[Element]) -> str:
    rows = []
    for e in elements:
        specs = _element_to_specs(e)
        rows.append(f"        {e.id!r}: {specs!r},")
    if not rows:
        return "{}"
    return "{\n" + "\n".join(rows) + "\n    }"


def _build_method_body(method, element: Element | None) -> str:
    action = method.action
    if action == "navigate":
        return "self.navigate()"
    if element is None:
        return "raise RuntimeError('element missing')"

    locator = f"self.locate({element.id!r})"
    if action == "click":
        return f"{locator}.click()"
    if action == "fill":
        return f"{locator}.fill({method.args[0] if method.args else 'value'})"
    if action == "select":
        return f"{locator}.select_option({method.args[0] if method.args else 'value'})"
    if action == "check":
        return f"{locator}.check()"
    if action == "wait":
        return f"{locator}.wait_for(state='visible')"
    if action == "expect_visible":
        return f"expect({locator}).to_be_visible()"
    if action == "expect_text":
        arg = method.args[0] if method.args else 'value'
        return f"expect({locator}).to_contain_text({arg})"
    return "pass"


def _build_method_params(method) -> str:
    if method.action in {"fill", "select", "expect_text"}:
        return ", " + ", ".join(f"{a}: str" for a in (method.args or ["value"]))
    return ""


def render_pom(plan: POMPlan, extraction: PageExtraction) -> str:
    by_id = {e.id: e for e in extraction.elements}
    selectors_dict = _format_selector_dict(extraction.elements)

    parts = [_HEADER.format(url=extraction.final_url)]
    parts.append(
        _CLASS_TPL.format(
            class_name=plan.class_name,
            url=extraction.final_url,
            selectors_dict=selectors_dict,
        )
    )

    for method in plan.methods:
        element = by_id.get(method.element_id)
        body = _build_method_body(method, element)
        parts.append(
            _METHOD_TPL.format(
                name=method.name,
                params=_build_method_params(method),
                intent=method.intent.replace('"""', "'''"),
                body=body,
            )
        )

    return "".join(parts)
